### ISSUE TITLE
[Help]  When using the reports-server, the mutation policy of kind PolicyReport has stopped working.

### ISSUE THREAD

**Issue by a-alekseenkov** [kyverno/reports-server#265]
I am using a mutation policy for the kind PolicyReport.
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-policy-report
  annotations:
    policies.kyverno.io/title: Adding the Helm-chart-name Field to PolicyReport
    policies.kyverno.io/category: Security
    policies.kyverno.io/subject: Kubernetes APIs
    policies.kyverno.io/description: >-
      Adding the Helm-chart-name Field to PolicyReport
spec:
  schemaValidation: false
  webhookTimeoutSeconds: 30
  background: false
  rules:
  - name: add-helm-chart-name
    match:
      any:
      - resources:
          kinds:
          - wgpolicyk8s.io/v1alpha2/PolicyReport
          operations:
          - CREATE
    preconditions:
      any:
      - key: "{{request.object.metadata.ownerReferences[0].kind}}"
        operator: Equals
        value: Pod
    context:
      - name: controller_reference
        apiCall:
          urlPath: "/api/v1/namespaces/{{ request.object.metadata.namespace }}/pods/{{ request.object.metadata.ownerReferences[0].name }}"
          jmesPath: "{name: metadata.ownerReferences[0].name, kind: metadata.ownerReferences[0].kind, api_version: metadata.ownerReferences[0].apiVersion}"
          default: '{ "kind": "no", "name": "no", "api_version": "no" }'
    mutate:
      patchesJson6902: |-
        - op: add
          path: "/metadata/labels/controller_reference_kind"
          value: {{ to_lower(to_string(controller_reference.kind)) || 'err' }}
        - op: add
          path: "/metadata/labels/controller_reference_name"
          value: {{ controller_reference.name || 'err' }}
```
Before using the reports-server, the result was as follows.

```
kubectl get  policyreports -n test -o json | jq '.items[].metadata | select((.ownerReferences[0]?.kind == "Pod")) | {ownerReferences ,labels}'
{
  "ownerReferences": [
    {
      "apiVersion": "v1",
      "kind": "Pod",
      "name": "nginx-test-7b88586bb5-khfbq",
      "uid": "667e45bb-1ce4-4865-bf71-65129dc3b38d"
    }
  ],
  "labels": {
    "app.kubernetes.io/managed-by": "kyverno",
    "controller_reference_kind": "replicaset",
    "controller_reference_name": "nginx-test-7b88586bb5"
  }
}
{
  "ownerReferences": [
    {
      "apiVersion": "v1",
      "kind": "Pod",
      "name": "wordpress-test-789496d77c-rkfqv",
      "uid": "8c76aa65-8ce7-4872-b557-5defa480c4c6"
    }
  ],
  "labels": {
    "app.kubernetes.io/managed-by": "kyverno",
    "controller_reference_kind": "replicaset",
    "controller_reference_name": "wordpress-test-789496d77c"
  }
}
{
  "ownerReferences": [
    {
      "apiVersion": "v1",
      "kind": "Pod",
      "name": "wordpress-test-mariadb-0",
      "uid": "ea446e66-5ece-482b-8961-c98160950946"
    }
  ],
  "labels": {
    "app.kubernetes.io/managed-by": "kyverno",
    "controller_reference_kind": "statefulset",
    "controller_reference_name": "wordpress-test-mariadb"
  }
}
```

Using the reports-server caused labels to disappear.
```
kubectl get  policyreports -n test -o json | jq '.items[].metadata | select((.ownerReferences[0]?.kind == "Pod")) | {ownerReferences ,labels}'
{
 "ownerReferences": [
   {
     "apiVersion": "v1",
     "kind": "Pod",
     "name": "nginx-test-7b88586bb5-5g9wm",
     "uid": "3faf7f89-a0cc-4dfb-9117-3c0e685e5f22"
   }
 ],
 "labels": {
   "app.kubernetes.io/managed-by": "kyverno"
 }
}
{
 "ownerReferences": [
   {
     "apiVersion": "v1",
     "kind": "Pod",
     "name": "wordpress-test-mariadb-0",
     "uid": "707e15ac-d904-49d9-b8ce-ab9f5f397b4f"
   }
 ],
 "labels": {
   "app.kubernetes.io/managed-by": "kyverno"
 }
}
{
 "ownerReferences": [
   {
     "apiVersion": "v1",
     "kind": "Pod",
     "name": "wordpress-test-789496d77c-p849r",
     "uid": "f6bb9488-0a74-45f4-b040-7dc594977523"
   }
 ],
 "labels": {
   "app.kubernetes.io/managed-by": "kyverno"
 }
}
```
